#include "Player/BloodstreamCharacter.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Interaction/BloodstreamInteractionComponent.h"
#include "Items/BloodstreamInventoryComponent.h"
#include "Items/BloodstreamEquipmentComponent.h"
#include "Mount/BloodstreamMountedTravelComponent.h"
ABloodstreamCharacter::ABloodstreamCharacter(){bUseControllerRotationYaw=false;GetCharacterMovement()->bOrientRotationToMovement=true;GetCharacterMovement()->RotationRate=FRotator(0,420,0);GetCharacterMovement()->MaxWalkSpeed=RunSpeed;GetCharacterMovement()->MaxAcceleration=900;GetCharacterMovement()->BrakingDecelerationWalking=750;GetCharacterMovement()->AirControl=.2f;GetCharacterMovement()->GetNavAgentPropertiesRef().bCanCrouch=true;CameraBoom=CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));CameraBoom->SetupAttachment(RootComponent);CameraBoom->TargetArmLength=330;CameraBoom->bUsePawnControlRotation=true;CameraBoom->bDoCollisionTest=true;CameraBoom->ProbeSize=14;CameraBoom->bEnableCameraLag=true;CameraBoom->CameraLagSpeed=14;FollowCamera=CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));FollowCamera->SetupAttachment(CameraBoom,USpringArmComponent::SocketName);FollowCamera->bUsePawnControlRotation=false;FollowCamera->FieldOfView=75;InteractionComponent=CreateDefaultSubobject<UBloodstreamInteractionComponent>(TEXT("Interaction"));InventoryComponent=CreateDefaultSubobject<UBloodstreamInventoryComponent>(TEXT("Inventory"));EquipmentComponent=CreateDefaultSubobject<UBloodstreamEquipmentComponent>(TEXT("Equipment"));MountedTravelComponent=CreateDefaultSubobject<UBloodstreamMountedTravelComponent>(TEXT("MountedTravel"));}
void ABloodstreamCharacter::Move(const FVector2D& V){if(PlayerMode==EBloodstreamPlayerMode::Mounted){MountedTravelComponent->Move(V);return;}if(PlayerMode!=EBloodstreamPlayerMode::FreeMovement||!Controller)return;const FRotator Y(0,Controller->GetControlRotation().Yaw,0);AddMovementInput(FRotationMatrix(Y).GetUnitAxis(EAxis::X),V.Y);AddMovementInput(FRotationMatrix(Y).GetUnitAxis(EAxis::Y),V.X);}
void ABloodstreamCharacter::Look(const FVector2D& V){if(PlayerMode==EBloodstreamPlayerMode::Disabled)return;AddControllerYawInput(V.X);AddControllerPitchInput(V.Y);}
void ABloodstreamCharacter::SetSprinting(bool B){if(PlayerMode!=EBloodstreamPlayerMode::FreeMovement)B=false;GetCharacterMovement()->MaxWalkSpeed=B?SprintSpeed:RunSpeed;}
void ABloodstreamCharacter::ToggleCrouch(){if(PlayerMode!=EBloodstreamPlayerMode::FreeMovement)return;bIsCrouched?UnCrouch():Crouch();}
bool ABloodstreamCharacter::SetPlayerMode(EBloodstreamPlayerMode N){if(PlayerMode==N)return true;if(InteractionComponent&&N==EBloodstreamPlayerMode::FreeMovement)InteractionComponent->CancelActive();PlayerMode=N;if(N!=EBloodstreamPlayerMode::FreeMovement)SetSprinting(false);ApplyMountedCamera(N==EBloodstreamPlayerMode::Mounted);return true;}
void ABloodstreamCharacter::ApplyMountedCamera(bool B){CameraBoom->TargetArmLength=B?430.f:330.f;CameraBoom->SocketOffset=B?FVector(0,55,80):FVector::ZeroVector;FollowCamera->FieldOfView=B?78.f:75.f;}
